version: '3'
volumes:
  postgres_data: {}

services:
  rainbow:
    container_name: rainbow
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - $PWD:/var/www/app
    ports:
      - 3000:3000
    networks:
      - rainbow-net
      - rainbow-priv
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER: postgres
      POSTGRES_DB: rainbow
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER: postgres
      POSTGRES_DB: rainbow
    networks:
      - rainbow-priv
#  web:
#    build:
#      context: .
#      dockerfile: docker/web/Dockerfile
#    depends_on:
#      - rainbow
#    ports:
#      - 80:80
networks:
  rainbow-net:
    external:
      name: rainbow-net
