version: '3'
volumes:
  postgres_data: {}

services:
  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    volumes:
      - $PWD:/var/www/app
    ports:
      - 7777:3000
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
